#!/bin/bash
# script for clearing cache folders

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
TMPCACHE=$DIR/../temp/cache
WWWCACHE=$DIR/../www/webtemp

echo "Clearing cache $TMPCACHE"
sudo rm -rf $TMPCACHE
echo "Clearing WWW cache $WWWCACHE"
sudo rm -rf $WWWCACHE/*
