#!/bin/bash
# script for simplifying deployment process

# update revision
echo "Fetching..."
git fetch
echo "Updating revision..."
git pull origin master

# install mandatory dependencies
echo "Updating composer dependencies..."
composer install

# delete cache
echo "Clearing cache..."
# TODO: handle correct current dir resolution
$PWD/tools/clear_cache

echo "All done!"
exit 0
